// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/common.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Pager struct {
	CurrentPage int32 `protobuf:"varint,1,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	TotalPage   int32 `protobuf:"varint,2,opt,name=total_page,json=totalPage" json:"total_page,omitempty"`
	Total       int32 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Current     int32 `protobuf:"varint,4,opt,name=current" json:"current,omitempty"`
}

func (m *Pager) Reset()                    { *m = Pager{} }
func (m *Pager) String() string            { return proto.CompactTextString(m) }
func (*Pager) ProtoMessage()               {}
func (*Pager) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Pager) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Pager) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *Pager) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pager) GetCurrent() int32 {
	if m != nil {
		return m.Current
	}
	return 0
}

type Query struct {
	Field string `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Query) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Query) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetByQuery struct {
	Query []*Query `protobuf:"bytes,1,rep,name=query" json:"query,omitempty"`
}

func (m *GetByQuery) Reset()                    { *m = GetByQuery{} }
func (m *GetByQuery) String() string            { return proto.CompactTextString(m) }
func (*GetByQuery) ProtoMessage()               {}
func (*GetByQuery) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetByQuery) GetQuery() []*Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type GetByID struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetByID) Reset()                    { *m = GetByID{} }
func (m *GetByID) String() string            { return proto.CompactTextString(m) }
func (*GetByID) ProtoMessage()               {}
func (*GetByID) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetByID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Pager)(nil), "protos.Pager")
	proto.RegisterType((*Query)(nil), "protos.Query")
	proto.RegisterType((*GetByQuery)(nil), "protos.GetByQuery")
	proto.RegisterType((*GetByID)(nil), "protos.GetByID")
}

func init() { proto.RegisterFile("protos/common.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x4f, 0x4f, 0xc3, 0x20,
	0x18, 0xc6, 0xd3, 0x4e, 0x5c, 0xfa, 0x4e, 0x3d, 0xe0, 0x0e, 0x78, 0xd0, 0xcc, 0x7a, 0xd9, 0x09,
	0xa3, 0xfb, 0x06, 0x8b, 0x89, 0xf1, 0xa6, 0x1c, 0xbd, 0x18, 0xb6, 0xe1, 0x82, 0x32, 0xa8, 0x14,
	0x4c, 0xea, 0xa7, 0x37, 0xbc, 0x6f, 0x77, 0x6a, 0x7f, 0xcf, 0x1f, 0x9e, 0x00, 0x5c, 0x76, 0x31,
	0xa4, 0xd0, 0xdf, 0x6f, 0xc3, 0xe1, 0x10, 0xbc, 0x44, 0xe2, 0xa7, 0x24, 0xb6, 0x03, 0xb0, 0x57,
	0xbd, 0x37, 0x91, 0xdf, 0xc2, 0xd9, 0x36, 0xc7, 0x68, 0x7c, 0xfa, 0xe8, 0xf4, 0xde, 0x88, 0x6a,
	0x51, 0x2d, 0x99, 0x9a, 0x8d, 0x5a, 0xc9, 0xf0, 0x6b, 0x80, 0x14, 0x92, 0x76, 0x14, 0xa8, 0x31,
	0xd0, 0xa0, 0x82, 0xf6, 0x1c, 0x18, 0x82, 0x98, 0xa0, 0x43, 0xc0, 0x05, 0x4c, 0xc7, 0x33, 0xc4,
	0x09, 0xea, 0x47, 0x6c, 0x57, 0xc0, 0xde, 0xb2, 0x89, 0x43, 0x29, 0x7e, 0x5a, 0xe3, 0x76, 0xb8,
	0xd9, 0x28, 0x82, 0xa2, 0xfe, 0x6a, 0x97, 0x69, 0xa8, 0x51, 0x04, 0xed, 0x03, 0xc0, 0xb3, 0x49,
	0xeb, 0x81, 0x9a, 0x77, 0xc0, 0x7e, 0xca, 0x8f, 0xa8, 0x16, 0x93, 0xe5, 0xec, 0xf1, 0x9c, 0x2e,
	0xd7, 0x4b, 0x74, 0x15, 0x79, 0xed, 0x15, 0x4c, 0xb1, 0xf2, 0xf2, 0xc4, 0x2f, 0xa0, 0xb6, 0xc7,
	0x99, 0xda, 0xee, 0xd6, 0x37, 0x30, 0xf7, 0xd6, 0x7f, 0x69, 0xd9, 0xeb, 0x6f, 0xbb, 0x91, 0x51,
	0x77, 0xd9, 0xff, 0x19, 0xf7, 0x3e, 0xbe, 0xce, 0x86, 0xbe, 0xab, 0xff, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x5b, 0xc7, 0xe7, 0x18, 0x43, 0x01, 0x00, 0x00,
}
