// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/comment.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	protos/comment.proto
	protos/common.proto
	protos/error.proto
	protos/post.proto
	protos/services.proto
	protos/session.proto
	protos/user.proto

It has these top-level messages:
	Comment
	ReqCommentCreate
	ResComment
	ReqCommentUpdate
	ResCommentSuccess
	ResCommentList
	Pager
	Query
	GetByQuery
	GetByID
	ErrorDetails
	Error
	Post
	ReqPostCreate
	ResPost
	ReqPostUpdate
	ResPostSuccess
	ReqPostChangeStatus
	ResPostList
	Session
	User
	ReqRegistration
	ResRegistration
	ReqLogin
	ResLogin
	ReqProfile
	ResProfile
	ReqUpdateUser
	ResUpdateUser
	ReqChangePassword
	ResChangePassword
	ReqChangeUserStatus
	ResChangeUserStatus
	ReqChangeUserType
	ResChangeUserType
	ReqUserLogout
	ResUserLogout
	ReqResetPasswordRequest
	ResResetPasswordRequest
	ReqResetPassword
	ResResetPassword
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Comment struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Body   string `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	PostId string `protobuf:"bytes,5,opt,name=post_id,json=postId" json:"post_id,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Comment) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Comment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Comment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Comment) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type ReqCommentCreate struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Body  string `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *ReqCommentCreate) Reset()                    { *m = ReqCommentCreate{} }
func (m *ReqCommentCreate) String() string            { return proto.CompactTextString(m) }
func (*ReqCommentCreate) ProtoMessage()               {}
func (*ReqCommentCreate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReqCommentCreate) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReqCommentCreate) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ResComment struct {
	Comment *Comment `protobuf:"bytes,1,opt,name=comment" json:"comment,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResComment) Reset()                    { *m = ResComment{} }
func (m *ResComment) String() string            { return proto.CompactTextString(m) }
func (*ResComment) ProtoMessage()               {}
func (*ResComment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResComment) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *ResComment) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqCommentUpdate struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Body  string `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
}

func (m *ReqCommentUpdate) Reset()                    { *m = ReqCommentUpdate{} }
func (m *ReqCommentUpdate) String() string            { return proto.CompactTextString(m) }
func (*ReqCommentUpdate) ProtoMessage()               {}
func (*ReqCommentUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReqCommentUpdate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReqCommentUpdate) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReqCommentUpdate) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ResCommentSuccess struct {
	Success bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=errors" json:"errors,omitempty"`
}

func (m *ResCommentSuccess) Reset()                    { *m = ResCommentSuccess{} }
func (m *ResCommentSuccess) String() string            { return proto.CompactTextString(m) }
func (*ResCommentSuccess) ProtoMessage()               {}
func (*ResCommentSuccess) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResCommentSuccess) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResCommentSuccess) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResCommentList struct {
	Comments []*Comment `protobuf:"bytes,1,rep,name=comments" json:"comments,omitempty"`
	Pager    *Pager     `protobuf:"bytes,2,opt,name=pager" json:"pager,omitempty"`
}

func (m *ResCommentList) Reset()                    { *m = ResCommentList{} }
func (m *ResCommentList) String() string            { return proto.CompactTextString(m) }
func (*ResCommentList) ProtoMessage()               {}
func (*ResCommentList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ResCommentList) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *ResCommentList) GetPager() *Pager {
	if m != nil {
		return m.Pager
	}
	return nil
}

func init() {
	proto.RegisterType((*Comment)(nil), "protos.Comment")
	proto.RegisterType((*ReqCommentCreate)(nil), "protos.ReqCommentCreate")
	proto.RegisterType((*ResComment)(nil), "protos.ResComment")
	proto.RegisterType((*ReqCommentUpdate)(nil), "protos.ReqCommentUpdate")
	proto.RegisterType((*ResCommentSuccess)(nil), "protos.ResCommentSuccess")
	proto.RegisterType((*ResCommentList)(nil), "protos.ResCommentList")
}

func init() { proto.RegisterFile("protos/comment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcf, 0x4b, 0xc3, 0x30,
	0x18, 0xa5, 0xed, 0xda, 0xce, 0x6f, 0x38, 0xf5, 0x73, 0x60, 0xd8, 0x69, 0x54, 0x84, 0x89, 0x30,
	0x61, 0x5e, 0xbd, 0x0d, 0x0f, 0x83, 0x1d, 0x24, 0xea, 0x55, 0x59, 0x9b, 0x20, 0x01, 0xb7, 0xd4,
	0x24, 0x3d, 0xf8, 0xdf, 0x4b, 0x7e, 0xd4, 0xf6, 0xb0, 0x83, 0xec, 0x96, 0xf7, 0xde, 0x97, 0xef,
	0xbd, 0x3c, 0x02, 0x93, 0x5a, 0x49, 0x23, 0xf5, 0x7d, 0x25, 0x77, 0x3b, 0xbe, 0x37, 0x0b, 0x07,
	0x31, 0xf3, 0xec, 0x14, 0x83, 0xca, 0x95, 0x92, 0xca, 0x6b, 0xd3, 0xcb, 0xde, 0x0d, 0xb9, 0xf7,
	0x64, 0xd1, 0x40, 0xbe, 0xf2, 0x1b, 0x70, 0x0c, 0xb1, 0x60, 0x24, 0x9a, 0x45, 0xf3, 0x13, 0x1a,
	0x0b, 0x86, 0x13, 0x48, 0x8d, 0x30, 0x5f, 0x9c, 0xc4, 0x8e, 0xf2, 0x00, 0x11, 0x06, 0xa5, 0x64,
	0x3f, 0x24, 0x71, 0xa4, 0x3b, 0xe3, 0x15, 0xe4, 0x8d, 0xe6, 0xea, 0x43, 0x30, 0x32, 0x70, 0x74,
	0x66, 0xe1, 0x9a, 0x59, 0xa1, 0x96, 0xda, 0x58, 0x21, 0xf5, 0x82, 0x85, 0x6b, 0x56, 0x3c, 0xc2,
	0x39, 0xe5, 0xdf, 0xc1, 0x79, 0xa5, 0xf8, 0xd6, 0xf0, 0xce, 0x2f, 0x3a, 0xe4, 0x17, 0x77, 0x7e,
	0xc5, 0x3b, 0x00, 0xe5, 0xba, 0xcd, 0x7d, 0x0b, 0x79, 0x28, 0xc1, 0xdd, 0x1c, 0x2d, 0xcf, 0xfc,
	0xdb, 0xf4, 0x22, 0x4c, 0xd0, 0x56, 0xc7, 0x1b, 0xc8, 0x5c, 0x23, 0x9a, 0xc4, 0xb3, 0x64, 0x3e,
	0x5a, 0x9e, 0xb6, 0x93, 0x4f, 0x96, 0xa5, 0x41, 0x2c, 0x36, 0xfd, 0x74, 0x6f, 0x35, 0xb3, 0xe9,
	0x8e, 0x6e, 0xa7, 0x78, 0x85, 0x8b, 0x2e, 0xed, 0x4b, 0x53, 0x55, 0x5c, 0x6b, 0x24, 0x90, 0x6b,
	0x7f, 0x74, 0x3b, 0x87, 0xb4, 0x85, 0xff, 0xcd, 0x58, 0xc2, 0xb8, 0xdb, 0xba, 0x11, 0xda, 0xe0,
	0x1d, 0x0c, 0xc3, 0x3b, 0xed, 0xce, 0xe4, 0x50, 0x11, 0x7f, 0x03, 0x78, 0x0d, 0x69, 0xbd, 0xfd,
	0xe4, 0xca, 0xc5, 0xef, 0x99, 0x3c, 0x5b, 0x92, 0x7a, 0xad, 0xf4, 0xbf, 0xe9, 0xe1, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xc2, 0x63, 0xa0, 0x2e, 0x6c, 0x02, 0x00, 0x00,
}
