// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type User struct {
	ID         string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Username   string `protobuf:"bytes,3,opt,name=Username" json:"Username,omitempty"`
	Email      string `protobuf:"bytes,4,opt,name=Email" json:"Email,omitempty"`
	Details    string `protobuf:"bytes,6,opt,name=Details" json:"Details,omitempty"`
	UserType   string `protobuf:"bytes,7,opt,name=UserType" json:"UserType,omitempty"`
	UserStatus string `protobuf:"bytes,8,opt,name=UserStatus" json:"UserStatus,omitempty"`
	CreatedAt  string `protobuf:"bytes,9,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	UpdatedAt  string `protobuf:"bytes,10,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *User) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

func (m *User) GetUserStatus() string {
	if m != nil {
		return m.UserStatus
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ReqRegistration struct {
	Name     string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=Password" json:"Password,omitempty"`
	Details  string `protobuf:"bytes,5,opt,name=Details" json:"Details,omitempty"`
}

func (m *ReqRegistration) Reset()                    { *m = ReqRegistration{} }
func (m *ReqRegistration) String() string            { return proto.CompactTextString(m) }
func (*ReqRegistration) ProtoMessage()               {}
func (*ReqRegistration) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *ReqRegistration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqRegistration) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqRegistration) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReqRegistration) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ReqRegistration) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type ResRegistration struct {
	User   *User    `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Errors []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResRegistration) Reset()                    { *m = ResRegistration{} }
func (m *ResRegistration) String() string            { return proto.CompactTextString(m) }
func (*ResRegistration) ProtoMessage()               {}
func (*ResRegistration) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *ResRegistration) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResRegistration) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqLogin struct {
	Username string `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *ReqLogin) Reset()                    { *m = ReqLogin{} }
func (m *ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()               {}
func (*ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *ReqLogin) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResLogin struct {
	Session *Session `protobuf:"bytes,1,opt,name=Session" json:"Session,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResLogin) Reset()                    { *m = ResLogin{} }
func (m *ResLogin) String() string            { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()               {}
func (*ResLogin) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

func (m *ResLogin) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *ResLogin) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqProfile struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *ReqProfile) Reset()                    { *m = ReqProfile{} }
func (m *ReqProfile) String() string            { return proto.CompactTextString(m) }
func (*ReqProfile) ProtoMessage()               {}
func (*ReqProfile) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

func (m *ReqProfile) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ResProfile struct {
	User   *User    `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Errors []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResProfile) Reset()                    { *m = ResProfile{} }
func (m *ResProfile) String() string            { return proto.CompactTextString(m) }
func (*ResProfile) ProtoMessage()               {}
func (*ResProfile) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *ResProfile) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResProfile) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqUpdateUser struct {
	Name    string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=Details" json:"Details,omitempty"`
}

func (m *ReqUpdateUser) Reset()                    { *m = ReqUpdateUser{} }
func (m *ReqUpdateUser) String() string            { return proto.CompactTextString(m) }
func (*ReqUpdateUser) ProtoMessage()               {}
func (*ReqUpdateUser) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

func (m *ReqUpdateUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqUpdateUser) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type ResUpdateUser struct {
	User   *User    `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Errors []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResUpdateUser) Reset()                    { *m = ResUpdateUser{} }
func (m *ResUpdateUser) String() string            { return proto.CompactTextString(m) }
func (*ResUpdateUser) ProtoMessage()               {}
func (*ResUpdateUser) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

func (m *ResUpdateUser) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResUpdateUser) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqChangePassword struct {
	OldPassword string `protobuf:"bytes,1,opt,name=OldPassword" json:"OldPassword,omitempty"`
	NewPassword string `protobuf:"bytes,2,opt,name=NewPassword" json:"NewPassword,omitempty"`
}

func (m *ReqChangePassword) Reset()                    { *m = ReqChangePassword{} }
func (m *ReqChangePassword) String() string            { return proto.CompactTextString(m) }
func (*ReqChangePassword) ProtoMessage()               {}
func (*ReqChangePassword) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{9} }

func (m *ReqChangePassword) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ReqChangePassword) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResChangePassword struct {
	Success bool     `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResChangePassword) Reset()                    { *m = ResChangePassword{} }
func (m *ResChangePassword) String() string            { return proto.CompactTextString(m) }
func (*ResChangePassword) ProtoMessage()               {}
func (*ResChangePassword) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{10} }

func (m *ResChangePassword) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResChangePassword) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqChangeUserStatus struct {
	UserID    string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	NewStatus string `protobuf:"bytes,2,opt,name=NewStatus" json:"NewStatus,omitempty"`
}

func (m *ReqChangeUserStatus) Reset()                    { *m = ReqChangeUserStatus{} }
func (m *ReqChangeUserStatus) String() string            { return proto.CompactTextString(m) }
func (*ReqChangeUserStatus) ProtoMessage()               {}
func (*ReqChangeUserStatus) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{11} }

func (m *ReqChangeUserStatus) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ReqChangeUserStatus) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

type ResChangeUserStatus struct {
	Success bool     `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResChangeUserStatus) Reset()                    { *m = ResChangeUserStatus{} }
func (m *ResChangeUserStatus) String() string            { return proto.CompactTextString(m) }
func (*ResChangeUserStatus) ProtoMessage()               {}
func (*ResChangeUserStatus) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{12} }

func (m *ResChangeUserStatus) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResChangeUserStatus) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqChangeUserType struct {
	UserID  string `protobuf:"bytes,1,opt,name=UserID" json:"UserID,omitempty"`
	NewType string `protobuf:"bytes,2,opt,name=NewType" json:"NewType,omitempty"`
}

func (m *ReqChangeUserType) Reset()                    { *m = ReqChangeUserType{} }
func (m *ReqChangeUserType) String() string            { return proto.CompactTextString(m) }
func (*ReqChangeUserType) ProtoMessage()               {}
func (*ReqChangeUserType) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{13} }

func (m *ReqChangeUserType) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ReqChangeUserType) GetNewType() string {
	if m != nil {
		return m.NewType
	}
	return ""
}

type ResChangeUserType struct {
	Success bool     `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResChangeUserType) Reset()                    { *m = ResChangeUserType{} }
func (m *ResChangeUserType) String() string            { return proto.CompactTextString(m) }
func (*ResChangeUserType) ProtoMessage()               {}
func (*ResChangeUserType) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{14} }

func (m *ResChangeUserType) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResChangeUserType) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqUserLogout struct {
	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken" json:"AccessToken,omitempty"`
}

func (m *ReqUserLogout) Reset()                    { *m = ReqUserLogout{} }
func (m *ReqUserLogout) String() string            { return proto.CompactTextString(m) }
func (*ReqUserLogout) ProtoMessage()               {}
func (*ReqUserLogout) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{15} }

func (m *ReqUserLogout) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type ResUserLogout struct {
	Success bool     `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResUserLogout) Reset()                    { *m = ResUserLogout{} }
func (m *ResUserLogout) String() string            { return proto.CompactTextString(m) }
func (*ResUserLogout) ProtoMessage()               {}
func (*ResUserLogout) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{16} }

func (m *ResUserLogout) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResUserLogout) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqResetPasswordRequest struct {
	Username string `protobuf:"bytes,1,opt,name=Username" json:"Username,omitempty"`
}

func (m *ReqResetPasswordRequest) Reset()                    { *m = ReqResetPasswordRequest{} }
func (m *ReqResetPasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*ReqResetPasswordRequest) ProtoMessage()               {}
func (*ReqResetPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{17} }

func (m *ReqResetPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ResResetPasswordRequest struct {
	Success bool     `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResResetPasswordRequest) Reset()                    { *m = ResResetPasswordRequest{} }
func (m *ResResetPasswordRequest) String() string            { return proto.CompactTextString(m) }
func (*ResResetPasswordRequest) ProtoMessage()               {}
func (*ResResetPasswordRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{18} }

func (m *ResResetPasswordRequest) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResResetPasswordRequest) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ReqResetPassword struct {
	PasswordResetToken string `protobuf:"bytes,1,opt,name=PasswordResetToken" json:"PasswordResetToken,omitempty"`
	NewPassword        string `protobuf:"bytes,2,opt,name=NewPassword" json:"NewPassword,omitempty"`
}

func (m *ReqResetPassword) Reset()                    { *m = ReqResetPassword{} }
func (m *ReqResetPassword) String() string            { return proto.CompactTextString(m) }
func (*ReqResetPassword) ProtoMessage()               {}
func (*ReqResetPassword) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{19} }

func (m *ReqResetPassword) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

func (m *ReqResetPassword) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ResResetPassword struct {
	Success bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Errors  []*Error `protobuf:"bytes,2,rep,name=Errors" json:"Errors,omitempty"`
}

func (m *ResResetPassword) Reset()                    { *m = ResResetPassword{} }
func (m *ResResetPassword) String() string            { return proto.CompactTextString(m) }
func (*ResResetPassword) ProtoMessage()               {}
func (*ResResetPassword) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{20} }

func (m *ResResetPassword) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResResetPassword) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "protos.User")
	proto.RegisterType((*ReqRegistration)(nil), "protos.ReqRegistration")
	proto.RegisterType((*ResRegistration)(nil), "protos.ResRegistration")
	proto.RegisterType((*ReqLogin)(nil), "protos.ReqLogin")
	proto.RegisterType((*ResLogin)(nil), "protos.ResLogin")
	proto.RegisterType((*ReqProfile)(nil), "protos.ReqProfile")
	proto.RegisterType((*ResProfile)(nil), "protos.ResProfile")
	proto.RegisterType((*ReqUpdateUser)(nil), "protos.ReqUpdateUser")
	proto.RegisterType((*ResUpdateUser)(nil), "protos.ResUpdateUser")
	proto.RegisterType((*ReqChangePassword)(nil), "protos.ReqChangePassword")
	proto.RegisterType((*ResChangePassword)(nil), "protos.ResChangePassword")
	proto.RegisterType((*ReqChangeUserStatus)(nil), "protos.ReqChangeUserStatus")
	proto.RegisterType((*ResChangeUserStatus)(nil), "protos.ResChangeUserStatus")
	proto.RegisterType((*ReqChangeUserType)(nil), "protos.ReqChangeUserType")
	proto.RegisterType((*ResChangeUserType)(nil), "protos.ResChangeUserType")
	proto.RegisterType((*ReqUserLogout)(nil), "protos.ReqUserLogout")
	proto.RegisterType((*ResUserLogout)(nil), "protos.ResUserLogout")
	proto.RegisterType((*ReqResetPasswordRequest)(nil), "protos.ReqResetPasswordRequest")
	proto.RegisterType((*ResResetPasswordRequest)(nil), "protos.ResResetPasswordRequest")
	proto.RegisterType((*ReqResetPassword)(nil), "protos.ReqResetPassword")
	proto.RegisterType((*ResResetPassword)(nil), "protos.ResResetPassword")
}

func init() { proto.RegisterFile("protos/user.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xdd, 0x36, 0x49, 0xa7, 0x94, 0xd2, 0xa5, 0x02, 0x2b, 0x42, 0x55, 0x64, 0x81, 0x54,
	0x2e, 0x41, 0x14, 0x71, 0xe4, 0xd0, 0x36, 0x39, 0x54, 0x54, 0x21, 0xda, 0x24, 0x80, 0x22, 0x2e,
	0x6e, 0x33, 0x04, 0xd3, 0xd4, 0x8e, 0x3d, 0x6b, 0x45, 0xf0, 0x1f, 0xf8, 0xab, 0xfc, 0x06, 0xb4,
	0x1f, 0x76, 0xd6, 0x21, 0x41, 0x41, 0xe9, 0x29, 0x9e, 0x37, 0xbb, 0x6f, 0xdf, 0xcc, 0x9b, 0xdd,
	0xc0, 0xe1, 0x34, 0x8d, 0x45, 0x4c, 0xaf, 0x32, 0xc2, 0xb4, 0xa9, 0xbe, 0x59, 0x45, 0x43, 0x75,
	0x66, 0x52, 0x98, 0xa6, 0xb1, 0xc9, 0xd5, 0x8f, 0x0c, 0x46, 0x48, 0x14, 0xc6, 0x91, 0x46, 0xfd,
	0xdf, 0x0e, 0x6c, 0x0f, 0x08, 0x53, 0xf6, 0x10, 0xdc, 0xcb, 0x96, 0xe7, 0x34, 0x9c, 0x93, 0x5d,
	0xee, 0x5e, 0xb6, 0x18, 0x83, 0xed, 0x4e, 0x70, 0x87, 0x9e, 0xab, 0x10, 0xf5, 0xcd, 0xea, 0x50,
	0x93, 0x6b, 0x23, 0x89, 0x6f, 0x29, 0xbc, 0x88, 0xd9, 0x11, 0xec, 0xb4, 0xef, 0x82, 0x70, 0xe2,
	0x6d, 0xab, 0x84, 0x0e, 0x98, 0x07, 0xd5, 0x16, 0x8a, 0x20, 0x9c, 0x90, 0x57, 0x51, 0x78, 0x1e,
	0xe6, 0x5c, 0xfd, 0x1f, 0x53, 0xf4, 0xaa, 0x73, 0x2e, 0x19, 0xb3, 0x63, 0x00, 0xf9, 0xdd, 0x13,
	0x81, 0xc8, 0xc8, 0xab, 0xa9, 0xac, 0x85, 0xb0, 0x67, 0xb0, 0x7b, 0x91, 0x62, 0x20, 0x70, 0x74,
	0x26, 0xbc, 0x5d, 0x95, 0x9e, 0x03, 0x32, 0x3b, 0x98, 0x8e, 0x4c, 0x16, 0x74, 0xb6, 0x00, 0xfc,
	0x5f, 0x0e, 0x1c, 0x70, 0x4c, 0x38, 0x8e, 0x43, 0x12, 0x69, 0x20, 0xc2, 0x38, 0x2a, 0x6a, 0x75,
	0x56, 0xd4, 0xea, 0xae, 0xaa, 0x75, 0xcb, 0xae, 0xb5, 0x0e, 0xb5, 0x6e, 0x40, 0x34, 0x8b, 0xd3,
	0x91, 0x69, 0x42, 0x11, 0xdb, 0x7d, 0xd8, 0x29, 0xf5, 0xc1, 0x1f, 0x4a, 0x39, 0x54, 0x92, 0xd3,
	0xd0, 0x96, 0x28, 0x39, 0x7b, 0xa7, 0x0f, 0xb4, 0x53, 0xd4, 0x94, 0x18, 0xd7, 0x66, 0xbd, 0x80,
	0x4a, 0x5b, 0x5a, 0x4b, 0x9e, 0xdb, 0xd8, 0x3a, 0xd9, 0x3b, 0xdd, 0xcf, 0xd7, 0x28, 0x94, 0x9b,
	0xa4, 0x7f, 0x0e, 0x35, 0x8e, 0xc9, 0x55, 0x3c, 0x0e, 0xa3, 0x52, 0x3d, 0xce, 0x42, 0x3d, 0xb6,
	0x72, 0xb7, 0xac, 0xdc, 0xff, 0x22, 0x39, 0x48, 0x73, 0xbc, 0x84, 0x6a, 0x4f, 0x4f, 0x8f, 0xd1,
	0x76, 0x90, 0x9f, 0x6b, 0x60, 0x9e, 0xe7, 0xd7, 0x55, 0xf8, 0x1c, 0x80, 0x63, 0xd2, 0x4d, 0xe3,
	0xaf, 0xe1, 0x04, 0xd9, 0x13, 0xa8, 0x48, 0x4d, 0xc5, 0x1c, 0x9a, 0xc8, 0x1f, 0xc8, 0x55, 0x94,
	0xaf, 0xba, 0xb7, 0xf6, 0xbc, 0x83, 0x7d, 0x8e, 0x89, 0x1e, 0x0d, 0xb5, 0x6f, 0xd9, 0x1c, 0x58,
	0xce, 0xb9, 0x65, 0xe7, 0x3e, 0xcb, 0xed, 0x64, 0x6d, 0xbf, 0x37, 0x61, 0x9f, 0xe0, 0x90, 0x63,
	0x72, 0xf1, 0x2d, 0x88, 0xc6, 0x58, 0x8c, 0x50, 0x03, 0xf6, 0x3e, 0x4c, 0x46, 0x85, 0x4f, 0x5a,
	0xa3, 0x0d, 0xc9, 0x15, 0x1d, 0x9c, 0x2d, 0x38, 0x69, 0x43, 0x7e, 0x5f, 0x12, 0xd3, 0x02, 0xb1,
	0x07, 0xd5, 0x5e, 0x76, 0x73, 0x83, 0x44, 0x8a, 0xb4, 0xc6, 0xf3, 0x70, 0x5d, 0xb9, 0xef, 0xe1,
	0x71, 0x21, 0xd7, 0xba, 0xa5, 0x2b, 0xdc, 0x94, 0xf7, 0xb3, 0x83, 0x33, 0x73, 0xb9, 0xb5, 0xc8,
	0x39, 0xe0, 0x7f, 0x94, 0x64, 0xf4, 0x17, 0xd9, 0xc6, 0x22, 0xdb, 0x56, 0x4f, 0x8b, 0x87, 0x66,
	0x95, 0x44, 0x0f, 0xaa, 0x1d, 0x9c, 0xa9, 0xb7, 0xc9, 0x98, 0x6e, 0xc2, 0x52, 0x07, 0x0b, 0x9a,
	0x8d, 0xc5, 0xbd, 0xd6, 0x93, 0x48, 0x98, 0x5e, 0xc5, 0xe3, 0x38, 0x13, 0xd2, 0xca, 0x33, 0xc5,
	0xd0, 0x8f, 0x6f, 0x31, 0xca, 0xcd, 0xb6, 0x20, 0xbf, 0xab, 0xa7, 0x6f, 0xbe, 0x65, 0x63, 0x11,
	0x6f, 0xe1, 0xa9, 0x7a, 0x18, 0x09, 0x45, 0x3e, 0x1b, 0x1c, 0x93, 0x0c, 0x49, 0xfc, 0xeb, 0xf1,
	0xf0, 0x87, 0x72, 0x1b, 0x2d, 0xdd, 0xb6, 0xb1, 0xa4, 0x11, 0x3c, 0x5a, 0x94, 0xc4, 0x9a, 0xc0,
	0xe6, 0xe7, 0x10, 0x0a, 0xbb, 0x43, 0x4b, 0x32, 0x6b, 0xdc, 0x8a, 0x9e, 0x3c, 0xa5, 0x5c, 0x81,
	0x94, 0x4e, 0x65, 0xe9, 0xf4, 0x5f, 0xd2, 0xcf, 0x8f, 0xe1, 0x28, 0x0a, 0xa3, 0xef, 0x41, 0x93,
	0x82, 0xdb, 0xf0, 0xba, 0x99, 0x06, 0xd3, 0x2c, 0xfa, 0x89, 0x93, 0xa1, 0xf9, 0x8b, 0xbe, 0xd6,
	0xbf, 0x6f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x63, 0x64, 0xad, 0xc6, 0x07, 0x00, 0x00,
}
